# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-21 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stockedup', '0002_auto_20170321_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='phone',
        ),
    ]
